export const siteOrigin = new URL(
  process.env.NEXT_PUBLIC_SITE_URL?.trim() || "https://boundaryfirstlabs.com",
);

const vercelEnvironment = process.env.VERCEL_ENV?.trim().toLowerCase();
const indexingOverride =
  process.env.BFL_V3_INDEXABLE?.trim().toLowerCase() === "true";

export const institutionalIndexingEnabled =
  vercelEnvironment === "production" || indexingOverride;

export const institutionalContentNodeRoutes = [
  "/about/how-we-work",
  "/products/current",
  "/products/current/corpus-forge",
  "/products/current/agency-representation-audit",
  "/research/software",
  "/research/software/boundary-first-engineering",
  "/research/software/ontological-software",
  "/research/software/executable-representation",
  "/research/software/boundary-first-architecture",
  "/research/software/boundary-first-ux",
  "/research/software/verification-governance",
  "/research/applied-testbeds",
  "/research/applied-testbeds/weather",
  "/research/applied-testbeds/chess",
  "/research/applied-testbeds/soccer",
  "/research/formal-theory",
  "/research/formal-theory/boundary-theory",
  "/research/formal-theory/schemathematics",
  "/research/foundations",
  "/research/foundations/distinction",
  "/research/foundations/bound-distinction",
  "/research/foundations/bit",
  "/research/foundations/distinction-space",
] as const;

export const institutionalPublicRoutes = [
  "/",
  "/about",
  "/apparatus",
  "/applied-work",
  "/ai-governance",
  "/atlas",
  "/changes",
  "/claims",
  "/collaboration",
  "/contact",
  "/evidence",
  "/experiments",
  "/labs/distinction-space",
  "/labs/representation-lab",
  "/founder",
  "/funding",
  "/lab-through-time",
  "/now",
  "/open-lab",
  "/products",
  "/products/agentic-scientific-method",
  "/products/boundary-first-chess",
  "/products/boundary-first-weather",
  "/products/youtube-knowledge-explorer",
  "/projects",
  "/projects/augusta-maintenance-debt",
  "/publications",
  "/representation-atlas",
  "/research",
  "/research/paper-mine",
  ...institutionalContentNodeRoutes,
  "/research/moonshots",
  "/research/moonshots/research-operating-system",
  "/research/moonshots/distributed-scientific-intelligence",
  "/research/moonshots/mathematical-interoperability",
  "/research/moonshots/executable-science",
  "/research/moonshots/formal-representation-mechanics",
  "/research/moonshots/self-improving-research-infrastructure",
  "/research/moonshots/millennium-problems-research",
  "/research/moonshots/fine-structure-constant",
  "/start",
] as const;
