import { PUBLIC_CONTACT_MAILTO } from "@/lib/site-contact";
import { PRIMARY_NAV_ITEMS } from "@/lib/site-navigation";

// The institutional header and legacy/immersive headers share one menu owner.
export const institutionalRoutes = PRIMARY_NAV_ITEMS;

const institutionalChildPages = {
  research: {
    label: "Research & Methods",
    href: "/research",
    relation: "QUESTIONS",
    kind: "observatory",
    tone: "indigo",
  },
  funding: {
    label: "Funding",
    href: "/funding",
    relation: "SUPPORT",
    kind: "support",
    tone: "gold",
  },
  appliedWork: {
    label: "Applied Work",
    href: "/applied-work",
    relation: "APPLICATION",
    kind: "application",
    tone: "orange",
  },
  evidence: {
    label: "Evidence",
    href: "/evidence",
    relation: "VALIDATION",
    kind: "evidence",
    tone: "green",
  },
  experiments: {
    label: "Experiments",
    href: "/experiments",
    relation: "TESTING",
    kind: "experiment",
    tone: "orange",
  },
  claims: {
    label: "Claims",
    href: "/claims",
    relation: "ASSERTIONS",
    kind: "claim",
    tone: "gold",
  },
  now: {
    label: "Now",
    href: "/now",
    relation: "STATUS",
    kind: "status",
    tone: "blue",
  },
  changes: {
    label: "What changed",
    href: "/changes",
    relation: "DELTA",
    kind: "status",
    tone: "green",
  },
  collaboration: {
    label: "Collaboration",
    href: "/collaboration",
    relation: "PARTICIPATION",
    kind: "participation",
    tone: "teal",
  },
  founder: {
    label: "Founder",
    href: "/founder",
    relation: "PROVENANCE",
    kind: "provenance",
    tone: "slate",
  },
  labThroughTime: {
    label: "Lab Through Time",
    href: "/lab-through-time",
    relation: "HISTORY",
    kind: "provenance",
    tone: "slate",
  },
  aiGovernance: {
    label: "AI Governance",
    href: "/ai-governance",
    relation: "AI CONTROL",
    kind: "governance",
    tone: "orange",
  },
  apparatus: {
    label: "Apparatus",
    href: "/apparatus",
    relation: "MACHINERY",
    kind: "apparatus",
    tone: "indigo",
  },
  atlas: {
    label: "Lab Atlas",
    href: "/atlas",
    relation: "MAP",
    kind: "atlas",
    tone: "indigo",
  },
  paperMine: {
    label: "Paper Mine",
    href: "/research/paper-mine",
    relation: "FULL CATALOG",
    kind: "apparatus",
    tone: "indigo",
  },
  representationAtlas: {
    label: "Representation Atlas",
    href: "/representation-atlas",
    relation: "LENS",
    kind: "atlas",
    tone: "teal",
  },
  observatory: {
    label: "Observatory",
    href: "/observatory",
    relation: "INSPECTION",
    kind: "observatory",
    tone: "indigo",
  },
} as const;

export const institutionalChildRoutes = {
  about: [
    institutionalChildPages.founder,
    institutionalChildPages.labThroughTime,
    institutionalChildPages.aiGovernance,
    institutionalChildPages.observatory,
    institutionalChildPages.now,
    institutionalChildPages.collaboration,
  ],
  research: [
    institutionalChildPages.observatory,
    institutionalChildPages.atlas,
    institutionalChildPages.representationAtlas,
    institutionalChildPages.experiments,
    institutionalChildPages.claims,
    institutionalChildPages.apparatus,
  ],
  products: [
    institutionalChildPages.appliedWork,
    institutionalChildPages.evidence,
    institutionalChildPages.collaboration,
    institutionalChildPages.now,
  ],
  projects: [
    institutionalChildPages.appliedWork,
    institutionalChildPages.aiGovernance,
    institutionalChildPages.evidence,
    institutionalChildPages.now,
    institutionalChildPages.collaboration,
    institutionalChildPages.apparatus,
  ],
  publications: [
    institutionalChildPages.observatory,
    institutionalChildPages.paperMine,
    institutionalChildPages.evidence,
    institutionalChildPages.claims,
    institutionalChildPages.experiments,
    institutionalChildPages.atlas,
  ],
  funding: [
    institutionalChildPages.now,
    institutionalChildPages.appliedWork,
    institutionalChildPages.evidence,
    institutionalChildPages.collaboration,
  ],
  collaboration: [
    institutionalChildPages.appliedWork,
    institutionalChildPages.funding,
    institutionalChildPages.evidence,
    institutionalChildPages.now,
  ],
  appliedWork: [
    institutionalChildPages.aiGovernance,
    institutionalChildPages.evidence,
    institutionalChildPages.collaboration,
    institutionalChildPages.funding,
    institutionalChildPages.now,
  ],
  aiGovernance: [
    institutionalChildPages.appliedWork,
    institutionalChildPages.evidence,
    institutionalChildPages.collaboration,
    institutionalChildPages.apparatus,
  ],
  founder: [
    institutionalChildPages.labThroughTime,
    institutionalChildPages.evidence,
    institutionalChildPages.observatory,
    institutionalChildPages.now,
    institutionalChildPages.collaboration,
  ],
  evidence: [
    institutionalChildPages.observatory,
    institutionalChildPages.claims,
    institutionalChildPages.experiments,
    institutionalChildPages.atlas,
    institutionalChildPages.now,
  ],
  now: [
    institutionalChildPages.observatory,
    institutionalChildPages.changes,
    institutionalChildPages.labThroughTime,
    institutionalChildPages.funding,
    institutionalChildPages.appliedWork,
    institutionalChildPages.collaboration,
  ],
  changes: [
    institutionalChildPages.observatory,
    institutionalChildPages.now,
    institutionalChildPages.labThroughTime,
    institutionalChildPages.atlas,
    institutionalChildPages.evidence,
    institutionalChildPages.apparatus,
  ],
  labThroughTime: [
    institutionalChildPages.observatory,
    institutionalChildPages.founder,
    institutionalChildPages.now,
    institutionalChildPages.changes,
    institutionalChildPages.evidence,
  ],
  apparatus: [
    institutionalChildPages.observatory,
    institutionalChildPages.experiments,
    institutionalChildPages.atlas,
    institutionalChildPages.evidence,
    institutionalChildPages.claims,
  ],
  experiments: [
    institutionalChildPages.observatory,
    institutionalChildPages.evidence,
    institutionalChildPages.claims,
    institutionalChildPages.apparatus,
    institutionalChildPages.atlas,
    institutionalChildPages.representationAtlas,
  ],
  claims: [
    institutionalChildPages.observatory,
    institutionalChildPages.evidence,
    institutionalChildPages.experiments,
    institutionalChildPages.atlas,
    institutionalChildPages.representationAtlas,
  ],
  atlas: [
    institutionalChildPages.observatory,
    institutionalChildPages.representationAtlas,
    institutionalChildPages.apparatus,
    institutionalChildPages.experiments,
    institutionalChildPages.claims,
    institutionalChildPages.evidence,
  ],
  representationAtlas: [
    institutionalChildPages.observatory,
    institutionalChildPages.atlas,
    institutionalChildPages.apparatus,
    institutionalChildPages.experiments,
    institutionalChildPages.collaboration,
  ],
  observatory: [
    institutionalChildPages.research,
    institutionalChildPages.atlas,
    institutionalChildPages.experiments,
    institutionalChildPages.evidence,
    institutionalChildPages.apparatus,
    institutionalChildPages.now,
  ],
  openLab: [
    institutionalChildPages.observatory,
    institutionalChildPages.collaboration,
    institutionalChildPages.aiGovernance,
    institutionalChildPages.experiments,
    institutionalChildPages.claims,
    institutionalChildPages.evidence,
  ],
  contact: [
    institutionalChildPages.collaboration,
    institutionalChildPages.appliedWork,
    institutionalChildPages.funding,
  ],
  start: [
    institutionalChildPages.appliedWork,
    institutionalChildPages.funding,
    institutionalChildPages.collaboration,
    institutionalChildPages.observatory,
    institutionalChildPages.atlas,
    institutionalChildPages.now,
  ],
} as const;

// Contextual footers retain deep links while mirroring the three visitor actions.
export const institutionalFooterGroups = [
  {
    label: "Institution",
    routes: [
      { label: "About", href: "/about" },
      { label: "Start here", href: "/start" },
      { label: "Founder", href: "/founder" },
      { label: "AI Governance", href: "/ai-governance" },
    ],
  },
  {
    label: "Products",
    routes: [
      { label: "Products", href: "/products" },
      { label: "Boundary-First Chess", href: "/products/boundary-first-chess" },
      { label: "Projectr / Knowledge Explorer", href: "/products/youtube-knowledge-explorer" },
      { label: "Boundary First Weather", href: "/products/boundary-first-weather" },
    ],
  },
  {
    label: "Observatory",
    routes: [
      { label: "Observatory", href: "/observatory" },
      { label: "Research & Methods", href: "/research" },
      { label: "Projects", href: "/projects" },
      { label: "Publications", href: "/publications" },
      { label: "Experiments", href: "/experiments" },
      { label: "Claims & Evidence", href: "/evidence" },
      { label: "Apparatus", href: "/apparatus" },
      { label: "Now / Roadmap", href: "/now" },
      { label: "Lab Through Time", href: "/lab-through-time" },
    ],
  },
  {
    label: "Work With Us",
    routes: [
      { label: "Work With Us", href: "/collaboration" },
      { label: "Applied Work", href: "/applied-work" },
      { label: "Open Lab / Critique", href: "/open-lab" },
      { label: "Funding", href: "/funding" },
      { label: "Contact", href: PUBLIC_CONTACT_MAILTO },
    ],
  },
] as const;

export const institutionalFooterRoutes = institutionalFooterGroups.flatMap<{
  readonly label: string;
  readonly href: string;
}>((group) => group.routes);
