/* @generated by BFUX Layout Studio. Safe to replace as a whole file. */
import type { BfuxMachineLayoutSource } from "./bfux-layout-source";

export const bfuxAuthoredLayout = {
  schema: "bfux.machine-layout/v1",
  focus: {
    billboard: {
      width: 35,
      height: null,
      gapY: 0,
      visualWidth: 44,
      mazeScale: 1,
      mazeLeft: -18,
      visualPadX: 0.56,
      visualPadY: 0.42,
      copyPadX: 0.72,
      copyPadY: 0.56,
      titleScale: 1.38,
      controlsHeight: 2.2
    },
    anchorGrid: {
      spec: { columns: 8, rows: 6, visible: true },
      placements: []
    },
    placedParts: []
  },
  mid: {
    billboard: {
      width: 35,
      height: null,
      gapY: 0,
      visualWidth: 44,
      mazeScale: 1,
      mazeLeft: -18,
      visualPadX: 0.56,
      visualPadY: 0.42,
      copyPadX: 0.72,
      copyPadY: 0.56,
      titleScale: 1.32,
      controlsHeight: 2.2
    },
    anchorGrid: {
      spec: { columns: 8, rows: 6, visible: true },
      placements: []
    },
    placedParts: []
  }
} satisfies BfuxMachineLayoutSource;
