/* @generated by BFUX Layout Studio. Safe to replace as a whole file. */
import type { BfuxMachineLayoutSource } from "./bfux-layout-source";

export const bfuxAuthoredLayout = {
  schema: "bfux.machine-layout/v1",
  focus: {
    billboard: {
      width: 35,
      height: null,
      gapY: 0,
      visualWidth: 40,
      mazeScale: 0.92,
      mazeLeft: -14,
      visualPadX: 0.5,
      visualPadY: 0.36,
      copyPadX: 0.62,
      copyPadY: 0.48,
      titleScale: 1.6,
      controlsHeight: 2.5
    },
    anchorGrid: {
      spec: { columns: 8, rows: 6, visible: true },
      placements: []
    },
    placedParts: []
  },
  mid: {
    billboard: {
      width: 35,
      height: null,
      gapY: 0,
      visualWidth: 40,
      mazeScale: 0.92,
      mazeLeft: -14,
      visualPadX: 0.5,
      visualPadY: 0.36,
      copyPadX: 0.62,
      copyPadY: 0.48,
      titleScale: 1.55,
      controlsHeight: 2.5
    },
    anchorGrid: {
      spec: { columns: 8, rows: 6, visible: true },
      placements: []
    },
    placedParts: []
  }
} satisfies BfuxMachineLayoutSource;
