import type { BfuxMachineLayoutSource } from "./bfux-layout-source";

export const bfuxAuthoredLayoutSourcePath = "src/components/bfux/bfux-layout-authored.generated.ts";
export const bfuxAuthoredLayoutSourceMarker = "/* @generated by BFUX Layout Studio. Safe to replace as a whole file. */";

export function renderBfuxAuthoredLayoutSource(source: BfuxMachineLayoutSource) {
  return `${bfuxAuthoredLayoutSourceMarker}\nimport type { BfuxMachineLayoutSource } from \"./bfux-layout-source\";\n\nexport const bfuxAuthoredLayout = ${JSON.stringify(source, null, 2)} satisfies BfuxMachineLayoutSource;\n`;
}
