"use client";

import { useMemo, useState } from "react";
import styles from "./AtlasSpace.module.css";
import wiringStyles from "./AtlasSpaceWiring.module.css";
import depthStyles from "./AtlasSpaceDepth.module.css";
import { LocalAtlasChart } from "./LocalAtlasChart";
import {
  connectorKindLabels,
  defaultAtlasSpaceModel,
  relationKindLabels,
  type AtlasFiber,
  type AtlasLayer,
  type AtlasPosition,
  type AtlasSpaceModel,
} from "./atlas-space-model";

type AtlasViewMode = "woven" | "focus";
type Point = { x: number; y: number };
type AtlasSpaceProps = { model?: AtlasSpaceModel; initialLayerId?: string; className?: string };

const GRID_STOPS = [25, 50, 75] as const;
const EDGE_X = 852;
const BACKPLANE_X = 884;

function cx(...values: Array<string | false | null | undefined>) { return values.filter(Boolean).join(" "); }
function layerLevel(layer: AtlasLayer, layers: AtlasLayer[]) { return Math.max(0, layers.length - 1 - layers.findIndex((item) => item.id === layer.id)); }
function project(position: AtlasPosition, level: number, mode: AtlasViewMode, extracted = false): Point {
  const u = position.x / 100; const v = position.y / 100;
  if (mode === "focus" && extracted) return { x: 90 + u * 650 + v * 126, y: 262 - u * 78 + v * 238 };
  const recession = mode === "focus" ? 0.82 : 1;
  return { x: 118 + u * 560 * recession + v * 132 * recession, y: 440 - u * 58 * recession + v * 152 * recession - level * 78 };
}
function polygonPoints(level: number, mode: AtlasViewMode, extracted = false) {
  return [project({ x: 0, y: 0 }, level, mode, extracted), project({ x: 100, y: 0 }, level, mode, extracted), project({ x: 100, y: 100 }, level, mode, extracted), project({ x: 0, y: 100 }, level, mode, extracted)].map((point) => `${point.x},${point.y}`).join(" ");
}
function edgePoint(layer: AtlasLayer, layers: AtlasLayer[]) { const boardEdge = project({ x: 100, y: 52 }, layerLevel(layer, layers), "woven"); return { x: EDGE_X, y: boardEdge.y }; }
function backplaneChannelX(index: number) { return BACKPLANE_X + index * 8; }
function routedPath(anchor: Point, edge: Point, channelX: number) { const doglegX = Math.max(anchor.x + 30, edge.x - 42); return `M ${anchor.x} ${anchor.y} L ${doglegX} ${anchor.y} L ${doglegX} ${edge.y} L ${edge.x} ${edge.y} L ${channelX} ${edge.y}`; }
function connectorClass(kind: AtlasFiber["connectorKind"]) { return wiringStyles[`connector_${kind}`]; }
function Screw({ className }: { className: string }) { return <span aria-hidden="true" className={cx(styles.screw, className)} />; }

export function AtlasSpace({ model = defaultAtlasSpaceModel, initialLayerId, className }: AtlasSpaceProps) {
  const firstLayerId = model.layers[0]?.id ?? ""; const firstFiberId = model.fibers[0]?.id ?? "";
  const resolvedInitialLayer = model.layers.some((layer) => layer.id === initialLayerId) ? (initialLayerId ?? firstLayerId) : firstLayerId;
  const [viewMode, setViewMode] = useState<AtlasViewMode>("woven"); const [activeLayerId, setActiveLayerId] = useState(resolvedInitialLayer); const [activeFiberId, setActiveFiberId] = useState(firstFiberId); const [showFibers, setShowFibers] = useState(true);
  const activeLayer = model.layers.find((layer) => layer.id === activeLayerId) ?? model.layers[0]; const activeFiber = model.fibers.find((fiber) => fiber.id === activeFiberId) ?? model.fibers[0];
  const renderLayers = useMemo(() => viewMode === "focus" ? [...model.layers.filter((layer) => layer.id !== activeLayerId), activeLayer] : model.layers, [activeLayer, activeLayerId, model.layers, viewMode]);
  if (!activeLayer || !activeFiber) return <section className={cx(styles.root, className)}><p className={styles.emptyState}>Atlas Space requires at least one layer and one fiber.</p></section>;

  return <section className={cx(styles.root, className)} aria-labelledby={`${model.id}-title`}>
    <Screw className={styles.screwTl} /><Screw className={styles.screwTr} /><Screw className={styles.screwBl} /><Screw className={styles.screwBr} />
    <header className={styles.header}><div className={styles.brandPlate}><span className={styles.brandMark}>BF</span><div><p>Boundary First Labs</p><small>Atlas instrumentation / prototype 00</small></div></div><div className={styles.statusStrip}><span><i /> correspondence bus online</span><span>representation is the control</span><span>{model.layers.length} atlas boards mounted</span></div></header>
    <div className={styles.instrumentGrid}>
      <aside className={styles.leftBank} aria-label="Atlas controls"><div className={styles.moduleLabel}>DEPTH CONTROL</div><div className={styles.toggleStack}><button type="button" aria-pressed={viewMode === "woven"} className={cx(styles.bankButton, viewMode === "woven" && styles.bankButtonActive)} onClick={() => setViewMode("woven")}><span className={styles.indicator} /> STACK</button><button type="button" aria-pressed={viewMode === "focus"} className={cx(styles.bankButton, viewMode === "focus" && styles.bankButtonActive)} onClick={() => setViewMode("focus")}><span className={styles.indicator} /> EXTRACT</button></div><div className={styles.moduleLabel}>BOARD MAGAZINE</div><nav className={styles.layerStack} aria-label="Atlas layers">{model.layers.map((layer) => <button type="button" key={layer.id} aria-current={layer.id === activeLayer.id ? "true" : undefined} className={cx(styles.layerButton, layer.id === activeLayer.id && styles.layerButtonActive)} onClick={() => setActiveLayerId(layer.id)}><span className={styles.channelNumber}>{layer.hardware.rackCode}</span><span><strong>{layer.label}</strong><small>{layer.hardware.registry}</small></span><i className={styles.layerLamp} /></button>)}</nav><div className={styles.moduleLabel}>BUS MASTER</div><button type="button" aria-pressed={showFibers} className={cx(styles.masterSwitch, showFibers && styles.masterSwitchOn)} onClick={() => setShowFibers((value) => !value)}><span className={styles.switchTrack}><i /></span><span>{showFibers ? "FIBERS ON" : "FIBERS OFF"}</span></button></aside>

      <div className={styles.centerAssembly}><div className={styles.screenBezel}><div className={styles.screenHeader}><span>ATLAS SPACE // {viewMode === "woven" ? "STACK" : `EXTRACT ${activeLayer.hardware.rackCode}`}</span><span className={styles.screenState}><i /> LIVE</span></div><div className={styles.viewport} data-view-mode={viewMode}><svg className={styles.canvas} viewBox="0 0 960 680" role="img" aria-label="Layered atlas boards connected through a typed rear correspondence backplane"><title>Boundary First Atlas Space layered atlas visualization</title><defs><filter id="atlasGlow" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="2.2" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><pattern id="ruled" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M0 14 H28" className={depthStyles.boardPatternLine} /></pattern><pattern id="wave" width="42" height="28" patternUnits="userSpaceOnUse"><path d="M0 14 C10 2 20 26 42 14" className={depthStyles.boardPatternLine} /></pattern><pattern id="logic" width="34" height="34" patternUnits="userSpaceOnUse"><path d="M4 17 H16 V7 H30 M16 17 V29 H30" className={depthStyles.boardPatternLine} /></pattern><pattern id="docket" width="40" height="32" patternUnits="userSpaceOnUse"><path d="M4 7 H36 M4 16 H28 M4 25 H34" className={depthStyles.boardPatternLine} /></pattern></defs>
        {renderLayers.map((layer) => { const level = layerLevel(layer, model.layers); const isActive = layer.id === activeLayer.id; const extracted = viewMode === "focus" && isActive; const labelPoint = project({ x: 3, y: 8 }, level, viewMode, extracted); const markPoint = project({ x: 91, y: 11 }, level, viewMode, extracted); return <g key={layer.id} className={cx(depthStyles.boardGroup, viewMode === "focus" && !isActive && depthStyles.boardRecessed, extracted && depthStyles.boardExtracted)}><polygon points={polygonPoints(level, viewMode, extracted)} className={cx(styles.boardShadow, isActive && styles.boardShadowActive)} /><polygon points={polygonPoints(level, viewMode, extracted)} className={cx(styles.board, isActive && styles.boardActive)} onClick={() => setActiveLayerId(layer.id)} /><polygon points={polygonPoints(level, viewMode, extracted)} fill={`url(#${layer.hardware.pattern})`} className={depthStyles.boardPattern} />{GRID_STOPS.map((stop) => { const a = project({ x: stop, y: 0 }, level, viewMode, extracted); const b = project({ x: stop, y: 100 }, level, viewMode, extracted); const c = project({ x: 0, y: stop }, level, viewMode, extracted); const d = project({ x: 100, y: stop }, level, viewMode, extracted); return <g key={`${layer.id}-${stop}`} className={styles.gridLines}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} /><line x1={c.x} y1={c.y} x2={d.x} y2={d.y} /></g>; })}<text x={labelPoint.x} y={labelPoint.y} className={styles.layerLabel}>{layer.hardware.rackCode} // {layer.label.toUpperCase()}</text><text x={markPoint.x} y={markPoint.y} className={depthStyles.boardMark}>{layer.hardware.mark}</text><circle cx={labelPoint.x - 10} cy={labelPoint.y - 4} r="4" className={depthStyles.registrationHole} /><circle cx={markPoint.x + 14} cy={markPoint.y - 4} r="4" className={depthStyles.registrationHole} /></g>; })}
        {showFibers && <g opacity={viewMode === "focus" ? 0.45 : 1}><rect x="844" y="74" width="100" height="514" rx="8" className={wiringStyles.backplaneHousing} /><text x="894" y="96" textAnchor="middle" className={wiringStyles.backplaneLabel}>REAR BUS</text>{model.fibers.map((fiber, fiberIndex) => { const channelX = backplaneChannelX(fiberIndex); const participating = model.layers.filter((layer) => layer.anchors.some((anchor) => anchor.fiberId === fiber.id)); const ends = participating.map((layer) => edgePoint(layer, model.layers)); const minY = Math.min(...ends.map((p) => p.y)); const maxY = Math.max(...ends.map((p) => p.y)); const isActive = fiber.id === activeFiber.id; return <g key={fiber.id}><line x1={channelX} y1={minY} x2={channelX} y2={maxY} className={cx(wiringStyles.backplaneBus, connectorClass(fiber.connectorKind), isActive && wiringStyles.backplaneBusActive)} />{participating.map((layer) => { const anchor = project(fiber.position, layerLevel(layer, model.layers), "woven"); const edge = edgePoint(layer, model.layers); return <g key={`${fiber.id}-${layer.id}`}><path d={routedPath(anchor, edge, channelX)} className={wiringStyles.traceSleeve} /><path d={routedPath(anchor, edge, channelX)} className={cx(wiringStyles.boardTrace, connectorClass(fiber.connectorKind), isActive && wiringStyles.boardTraceActive)} /></g>; })}</g>; })}</g>}
        {renderLayers.flatMap((layer) => { const level = layerLevel(layer, model.layers); const isLayerActive = layer.id === activeLayer.id; const extracted = viewMode === "focus" && isLayerActive; return model.fibers.map((fiber) => { const anchor = layer.anchors.find((item) => item.fiberId === fiber.id); if (!anchor) return null; const point = project(fiber.position, level, viewMode, extracted); const isActive = fiber.id === activeFiber.id; return <g key={`${layer.id}-${fiber.id}`} className={cx(styles.anchor, isActive && styles.anchorActive, viewMode === "focus" && !isLayerActive && depthStyles.anchorRecessed)} onClick={() => { setActiveLayerId(layer.id); setActiveFiberId(fiber.id); }}><circle cx={point.x} cy={point.y} r={extracted ? 14 : 11} className={cx(styles.jackOuter, wiringStyles[`jack_${fiber.connectorKind}`])} /><circle cx={point.x} cy={point.y} r={extracted ? 8 : 6.5} className={styles.jackInner} /><circle cx={point.x} cy={point.y} r={isActive ? 3.8 : 2.8} className={cx(styles.anchorDot, isLayerActive && styles.anchorDotLayerActive)} filter={isActive ? "url(#atlasGlow)" : undefined} /><text x={point.x + 14} y={point.y - 11} className={cx(styles.anchorLabel, extracted && styles.anchorLabelFocus)}>{anchor.label}</text></g>; }); })}</svg>{viewMode === "focus" ? <LocalAtlasChart layer={activeLayer} fibers={model.fibers} activeFiberId={activeFiberId} onSelectFiber={setActiveFiberId} /> : null}<div className={styles.screenCornerReadout}>{viewMode === "focus" ? `EXTRACTED ${activeLayer.hardware.rackCode} // LOCAL CHART ONLINE` : "LOCAL JACK → EDGE CONTACT → REAR BUS"}</div></div></div><div className={styles.lowerDeck}><div className={styles.deckPlate}><span>ACTIVE BOARD</span><strong>{activeLayer.hardware.rackCode}</strong><small>{activeLayer.hardware.registry}</small></div><div className={styles.deckPlate}><span>ACTIVE CHANNEL</span><strong>{activeFiber.label}</strong><small>{connectorKindLabels[activeFiber.connectorKind]}</small></div><div className={styles.deckPlateWide}><span>DEPTH RULE</span><strong>Extraction changes view depth, not system membership.</strong><small>The selected card comes forward while its rack and backplane remain visible.</small></div></div></div>

      <aside className={styles.rightBank} aria-label="Correspondence inspector"><div className={styles.moduleLabel}>BOARD IDENTITY</div><div className={styles.readout}><span className={styles.readoutType}>{activeLayer.hardware.rackCode}</span><h3>{activeLayer.label}</h3><p>{activeLayer.description}</p></div><div className={styles.moduleLabel}>PATCH BAY</div><div className={styles.patchBay}>{model.fibers.map((fiber, index) => <button type="button" key={fiber.id} aria-pressed={fiber.id === activeFiber.id} className={cx(styles.patchRow, wiringStyles[`patch_${fiber.connectorKind}`], fiber.id === activeFiber.id && styles.patchRowActive)} onClick={() => setActiveFiberId(fiber.id)}><span className={styles.patchJack}><i /></span><span className={styles.patchCode}>{fiber.connectorKind === "through" ? "THR" : fiber.connectorKind === "keyed" ? "KEY" : "TST"}{String(index + 1).padStart(2, "0")}</span><span className={styles.patchName}>{fiber.label}</span></button>)}</div><div className={styles.moduleLabel}>CHANNEL READOUT</div><div className={styles.readout}><span className={styles.readoutType}>{relationKindLabels[activeFiber.relationKind]}</span><h3>{activeFiber.label}</h3><p>{activeFiber.statement}</p></div><div className={styles.layerReadout}><span>MECHANICAL ACTION</span><p>{viewMode === "focus" ? "Board is extracted for inspection. Its local chart is active while rack context remains visible." : "Board is seated in the atlas stack."}</p><button type="button" onClick={() => setViewMode(viewMode === "focus" ? "woven" : "focus")}>{viewMode === "focus" ? "RESEAT BOARD" : "EXTRACT BOARD"}</button></div></aside>
    </div><footer className={styles.footerStrip}><span>BF-ATLAS / CHART SPEC 0.4</span><span>{model.thesis}</span><span>STACK → EXTRACT → INSPECT → RESEAT</span></footer>
  </section>;
}